<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
  public function showNextEvents()
  {
    $query = $this->getEntityManager()->createQuery(
        "SELECT e FROM AppBundle:Event e
        WHERE e.date > NOW()limit 3"
  );
  return $query;
  }
  public function showPreviousEvents()
  {
    $query = $this->getEntityManager()->createQuery(
        "SELECT e FROM AppBundle:Event e
        WHERE date < NOW() ORDERBY e.date DESC"
  );
  return $query;
  }
}
