<?php

namespace AppBundle\Repository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends \Doctrine\ORM\EntityRepository
{
    public function showAllAction()
    {
      $query = $this->getEntityManager()->createQuery(
          'SELECT s FROM AppBundle:Lesson s ORDER BY s.startAt DESC'
      );
      return $query->getResult();
    }
}
