<?php

namespace AppBundle\Repository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
  public function showAllAction()
  {
    $query = $this->getEntityManager()->createQuery(
        'SELECT s FROM AppBundle:Subscription s ORDER BY s.subscriptionAt DESC'
    );
    return $query->getResult();
  }
 // Fonction pour récuperer les insciptions pour un prof via son id à terminer ???? Voir la pertinence de la requête
//    public function showSubscriptionByTeacherId($id)
  public function showMyStudentsAction($id)
      {
        $query = $this->getEntityManager()->createQuery(
            'SELECT u FROM AppBundle:User u JOIN  AppBundle:Subscription s WHERE s.teacher = ?1'
        );
        $query->setParameter(1, $id);

        return $query->getResult();
    }
//    {
//      $query = $this->getEntityManager()->createQuery(
//          'SELECT s FROM AppBundle:Subscription s WHERE teacher.id = ? ORDER BY s.subscriptionAt DESC'
//      );
//      $stmt =bb;
//      return $query->getResult();
//    }



}
